version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.0.2
jobs:
  test:
    executor:
      name: node/default
      tag: '12.13.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run unit tests
          command: yarn run test
      - store_artifacts:
          path: coverage
  coverage:
    steps:
      - codecov/upload:
          file: coverage
workflows:
  node-tests:
    jobs:
      - test
      - coverage
